version: '3.8'
services:
  elasticsearch:
    image: elasticsearch:8.15.2
    container_name: els
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false   # Disable security for development (not recommended for production)
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"  # Elasticsearch HTTP
    networks:
      - elk

  kibana:
    image: kibana:8.15.2
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200  # Kibana connects to Elasticsearch
    ports:
      - "5601:5601"  # Kibana web interface
    networks:
      - elk
    depends_on:
      - elasticsearch

volumes:
  elasticsearch-data:
    driver: local

networks:
  elk:
    driver: bridge
